server:
  port: 0
  
spring:
  application:
    name: microservice-load-balance
  cloud:
    consul:
      host: ${CONSUL_HOST}
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        health-check-path: /health
        health-check-interval: 30s

  ribbon:
    eureka:
      enabled: false
    ServerListRefreshInterval: 15000